INSERT INTO public.quiz_questions (question, options, answer, category) VALUES
('¿Quién es el autor de "Contrapunto"?', '["Aldous Huxley","Gustavo Adolfo Bécquer","Jorge Luis Borges","Stephen King"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Ciego en Gaza"?', '["Milan Kundera","Hermann Hesse","Charles Dickens","Aldous Huxley"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Dan Brown?', '["El mito de Sísifo","Las nieves del Kilimanjaro","La fortaleza digital","La caída de la casa Usher"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Los hermanos Karamázov"?', '["George Orwell","Laura Esquivel","Fiódor Dostoyevski","Arturo Pérez-Reverte"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Cuento de Navidad"?', '["Camilo José Cela","Charles Dickens","Gustavo Adolfo Bécquer","Virginia Woolf"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El corazón delator"?', '["Leo Tolstói","Edgar Allan Poe","Isabel Allende","Stephen King"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Final del juego"?', '["Jane Austen","Miguel de Unamuno","Julio Cortázar","Leo Tolstói"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La insoportable levedad del ser"?', '["Isaac Asimov","Milan Kundera","Ken Follett","Carlos Ruiz Zafón"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Las inquietudes de Shanti Andía"?', '["Arthur Conan Doyle","Isaac Asimov","George Orwell","Pío Baroja"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "París era una fiesta"?', '["Camilo José Cela","Ernest Hemingway","Mario Vargas Llosa","William Shakespeare"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Gabriel García Márquez?', '["Italiano","Español","Colombiano","Japonés"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La señora Dalloway"?', '["Pío Baroja","Virginia Woolf","Franz Kafka","Jorge Luis Borges"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Gabriel García Márquez?', '["El coronel no tiene quien le escriba","Persuasión","Por quién doblan las campanas","Muerte en el Nilo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Billy Budd"?', '["Mark Twain","Herman Melville","Ray Bradbury","Aldous Huxley"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Charles Dickens?', '["Generación del 27","Realismo","Realismo mágico","Generación del 98"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por H.P. Lovecraft?', '["Cuento de Navidad","Niebla","El color que cayó del cielo","El árbol de las brujas"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Historias de cronopios y de famas"?', '["Arturo Pérez-Reverte","H.P. Lovecraft","Julio Cortázar","Antonio Machado"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El umbral de la eternidad"?', '["William Shakespeare","George Orwell","Juan Rulfo","Ken Follett"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Fiódor Dostoyevski?', '["Boom latinoamericano","Fantasía épica","Renacimiento","Realismo"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Fiódor Dostoyevski?', '["Apocalipsis","Las aventuras de Huckleberry Finn","El jugador","Residencia en la tierra"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad alemán?', '["Jorge Luis Borges","Hermann Hesse","Umberto Eco","Victor Hugo"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El ser y la nada"?', '["Jean-Paul Sartre","Ken Follett","Umberto Eco","Aldous Huxley"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La peste"?', '["Hermann Hesse","Albert Camus","Isaac Asimov","Arturo Pérez-Reverte"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Drácula"?', '["Bram Stoker","Virginia Woolf","Aldous Huxley","Gabriel García Márquez"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Eva Luna"?', '["Umberto Eco","Ernest Hemingway","William Shakespeare","Isabel Allende"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Odas elementales"?', '["Leo Tolstói","Miguel de Cervantes","Pablo Neruda","Arturo Pérez-Reverte"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Animales fantásticos y dónde encontrarlos"?', '["Oscar Wilde","H.P. Lovecraft","J.K. Rowling","Julio Cortázar"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Hermann Hesse?', '["Novela policíaca","Modernismo","Renacimiento","Ciencia ficción"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Pío Baroja?', '["Chileno","Peruano","Español","Estadounidense"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Fahrenheit 451"?', '["Ray Bradbury","Federico García Lorca","Bram Stoker","Charles Dickens"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La tía Tula"?', '["Virginia Woolf","J.R.R. Tolkien","Miguel de Unamuno","Jane Austen"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Harry Potter y la cámara secreta"?', '["George Orwell","Aldous Huxley","Haruki Murakami","J.K. Rowling"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Camilo José Cela?', '["Boom latinoamericano","Siglo de Oro","Tremendismo","Esteticismo"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad chilena?', '["Albert Camus","Franz Kafka","Jane Austen","Gabriela Mistral"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Fiesta"?', '["Ken Follett","Oscar Wilde","Ernest Hemingway","Edgar Allan Poe"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Grandes esperanzas"?', '["Charles Dickens","Franz Kafka","Julio Cortázar","Camilo José Cela"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Miguel de Unamuno?', '["Británica","Checo","Español","Ruso"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Laura Esquivel?', '["Británica","Peruano","Mexicana","Checo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Las aventuras de Sherlock Holmes"?', '["Virginia Woolf","Federico García Lorca","Jean-Paul Sartre","Arthur Conan Doyle"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Stephen King?', '["Chileno","Estadounidense","Japonés","Mexicano"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por J.R.R. Tolkien?', '["Cuentos inconclusos de Númenor y la Tierra Media","El rey Lear","La caída de la casa Usher","Diez negritos"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El laberinto de la soledad"?', '["Isaac Asimov","Edgar Allan Poe","Ken Follett","Octavio Paz"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Edgar Allan Poe?', '["Chileno","Estadounidense","Mexicano","Colombiano"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Mono y esencia"?', '["Jane Austen","Carlos Ruiz Zafón","Aldous Huxley","Herman Melville"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Bram Stoker?', '["Fantasía épica","Existencialismo","Novela policíaca","Terror gótico"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Ernest Hemingway?', '["Lodore","Muerte en el Nilo","La sombra sobre Innsmouth","Adiós a las armas"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Estudio en escarlata"?', '["Charles Dickens","Arthur Conan Doyle","William Shakespeare","Jean-Paul Sartre"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Harry Potter y el cáliz de fuego"?', '["Fiódor Dostoyevski","J.K. Rowling","Herman Melville","Bram Stoker"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El código Da Vinci"?', '["Federico García Lorca","Dan Brown","Camilo José Cela","Jean-Paul Sartre"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Emma"?', '["J.R.R. Tolkien","Jane Austen","Pío Baroja","Jean-Paul Sartre"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El libro de las emociones"?', '["Laura Esquivel","Ernest Hemingway","Albert Camus","Isaac Asimov"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El resplandor"?', '["George Orwell","Agatha Christie","Stephen King","Gabriela Mistral"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Por quién doblan las campanas"?', '["Federico García Lorca","Ernest Hemingway","Arturo Pérez-Reverte","Hermann Hesse"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Oscar Wilde?', '["El príncipe feliz","El ser y la nada","Final del juego","Cien sonetos de amor"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Miguel de Cervantes?', '["Mexicana","Español","Peruano","Ruso"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La isla del día de antes"?', '["Aldous Huxley","Dan Brown","Miguel de Unamuno","Umberto Eco"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El escarabajo de oro"?', '["Edgar Allan Poe","George Orwell","Isabel Allende","William Shakespeare"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Anna Karénina"?', '["Mario Vargas Llosa","Leo Tolstói","J.R.R. Tolkien","Herman Melville"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El señor de los anillos"?', '["Carlos Ruiz Zafón","J.R.R. Tolkien","Virginia Woolf","Oscar Wilde"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Jean-Paul Sartre?', '["Novelas ejemplares","París era una fiesta","Los caminos de la libertad","Homenaje a Cataluña"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Pío Baroja?', '["La busca","Número cero","Carta al padre","La metamorfosis"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Diez negritos"?', '["Agatha Christie","Dan Brown","J.K. Rowling","Miguel de Unamuno"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Romancero gitano"?', '["Federico García Lorca","Miguel de Unamuno","Umberto Eco","Ray Bradbury"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La llamada de Cthulhu"?', '["Milan Kundera","Antonio Machado","Ray Bradbury","H.P. Lovecraft"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El capitán Alatriste"?', '["Arturo Pérez-Reverte","Franz Kafka","William Shakespeare","Miguel de Unamuno"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El fantasma de Canterville"?', '["Oscar Wilde","Milan Kundera","Haruki Murakami","Albert Camus"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Julio Cortázar?', '["Las armas secretas","Harry Potter y la cámara secreta","El forastero misterioso","Sueño de una noche de verano"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Las olas"?', '["Umberto Eco","Carlos Ruiz Zafón","Virginia Woolf","Jean-Paul Sartre"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Hermann Hesse?', '["Soledades","Residencia en la tierra","Pantaleón y las visitadoras","Siddhartha"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Narciso y Goldmundo"?', '["Bram Stoker","Isaac Asimov","Hermann Hesse","Oscar Wilde"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Resurrección"?', '["Hermann Hesse","Leo Tolstói","Gabriela Mistral","Jane Austen"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Moby-Dick"?', '["Albert Camus","Herman Melville","Victor Hugo","Haruki Murakami"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Miguel de Cervantes?', '["Romanticismo","Surrealismo","Novela histórica","Siglo de Oro"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Bestiario"?', '["Laura Esquivel","Julio Cortázar","Agatha Christie","William Shakespeare"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La abadía de Northanger"?', '["Gabriela Mistral","Jane Austen","Octavio Paz","Arthur Conan Doyle"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Homenaje a Cataluña"?', '["Mario Vargas Llosa","H.P. Lovecraft","Arthur Conan Doyle","George Orwell"]'::jsonb, 3, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad mexicana?', '["Laura Esquivel","Stephen King","Ray Bradbury","Dan Brown"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Leo Tolstói?', '["Realismo","Siglo de Oro","Terror cósmico","Thriller"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Haruki Murakami?', '["Yerma","El proceso","El mundo perdido","Crónica del pájaro que da cuerda al mundo"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El forastero misterioso"?', '["Albert Camus","Laura Esquivel","Mark Twain","Miguel de Cervantes"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Kafka en la orilla"?', '["William Shakespeare","Haruki Murakami","Mario Vargas Llosa","H.P. Lovecraft"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Sin blanca en París y Londres"?', '["Gabriel García Márquez","Mario Vargas Llosa","George Orwell","J.R.R. Tolkien"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Desolación"?', '["Gabriel García Márquez","Jorge Luis Borges","Mark Twain","Gabriela Mistral"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Memorias del subsuelo"?', '["Virginia Woolf","Arturo Pérez-Reverte","Fiódor Dostoyevski","Octavio Paz"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El juego de los abalorios"?', '["J.R.R. Tolkien","H.P. Lovecraft","Hermann Hesse","Bram Stoker"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Sputnik, mi amor"?', '["Haruki Murakami","Arturo Pérez-Reverte","Stephen King","Bram Stoker"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Gabriel García Márquez?', '["Fantasía","Realismo mágico","Posmodernismo","Boom latinoamericano"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La tía Julia y el escribidor"?', '["Ernest Hemingway","Juan Rulfo","Albert Camus","Mario Vargas Llosa"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Franz Kafka?', '["Generación Perdida","Terror gótico","Existencialismo","Novela policíaca"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a J.R.R. Tolkien?', '["Fantasía épica","Realismo mágico","Tremendismo","Distopía"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Un marido ideal"?', '["Hermann Hesse","Fiódor Dostoyevski","Oscar Wilde","Miguel de Unamuno"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Aldous Huxley?', '["El cerco de Numancia","Los miserables","La isla","Fundación"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Pío Baroja?', '["Novela histórica","Generación del 98","Generación del 27","Boom latinoamericano"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La fortaleza digital"?', '["Victor Hugo","Milan Kundera","Dan Brown","Albert Camus"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Oliver Twist"?', '["Carlos Ruiz Zafón","Charles Dickens","Isabel Allende","Mary Shelley"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Miguel de Unamuno?', '["Ciencia ficción","Generación del 98","Siglo de Oro","Romanticismo"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El péndulo de Foucault"?', '["Aldous Huxley","Umberto Eco","Oscar Wilde","Isaac Asimov"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La identidad"?', '["Milan Kundera","Juan Rulfo","Jean-Paul Sartre","Oscar Wilde"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Gregor la profecía del gris"?', '["Oscar Wilde","Suzanne Collins","Miguel de Unamuno","Gabriela Mistral"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Carta al padre"?', '["Aldous Huxley","Franz Kafka","Stephen King","Ernest Hemingway"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El viejo y el mar"?', '["Ernest Hemingway","Isabel Allende","Herman Melville","Octavio Paz"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Fundación"?', '["H.P. Lovecraft","Umberto Eco","Isaac Asimov","Oscar Wilde"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Leo Tolstói?', '["Chilena","Ruso","Español","Argentino"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El Llano en llamas"?', '["Juan Rulfo","Franz Kafka","Mark Twain","Octavio Paz"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Infancia, adolescencia y juventud"?', '["Gabriel García Márquez","Hermann Hesse","Leo Tolstói","Fiódor Dostoyevski"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El Silmarillion"?', '["Suzanne Collins","J.R.R. Tolkien","Pío Baroja","Carlos Ruiz Zafón"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Guerra y paz"?', '["Gabriela Mistral","Leo Tolstói","Carlos Ruiz Zafón","William Shakespeare"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Rayuela"?', '["Julio Cortázar","Ray Bradbury","Pablo Neruda","Arthur Conan Doyle"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Las moscas"?', '["Laura Esquivel","Jean-Paul Sartre","Aldous Huxley","Pío Baroja"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El libro de la risa y el olvido"?', '["Milan Kundera","Victor Hugo","Bram Stoker","Gabriela Mistral"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Un artista del hambre"?', '["Franz Kafka","Dan Brown","Octavio Paz","Jane Austen"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Al faro"?', '["J.R.R. Tolkien","Pablo Neruda","Arthur Conan Doyle","Virginia Woolf"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Federico García Lorca?', '["Chileno","Argentino","Español","Colombiano"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Umberto Eco?', '["Distopía","Thriller","Posmodernismo","Fantasía"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "En la colonia penitenciaria"?', '["Franz Kafka","Gabriel García Márquez","Isabel Allende","J.R.R. Tolkien"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Historia universal de la infamia"?', '["J.K. Rowling","Aldous Huxley","Jorge Luis Borges","Pío Baroja"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El caso de Charles Dexter Ward"?', '["Herman Melville","Jane Austen","H.P. Lovecraft","Miguel de Unamuno"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Confieso que he vivido"?', '["Suzanne Collins","Edgar Allan Poe","Pablo Neruda","Carlos Ruiz Zafón"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por William Shakespeare?', '["Macbeth","Crónica del pájaro que da cuerda al mundo","Omoo","El príncipe de la niebla"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "It"?', '["Laura Esquivel","Stephen King","Albert Camus","Gustavo Adolfo Bécquer"]'::jsonb, 1, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad argentino?', '["Gustavo Adolfo Bécquer","Oscar Wilde","Jorge Luis Borges","Ernest Hemingway"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El retrato de Dorian Gray"?', '["Fiódor Dostoyevski","Oscar Wilde","Arturo Pérez-Reverte","Agatha Christie"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Las aventuras de Tom Sawyer"?', '["Edgar Allan Poe","J.R.R. Tolkien","Ken Follett","Mark Twain"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "San Manuel Bueno, mártir"?', '["Miguel de Unamuno","Jane Austen","Laura Esquivel","Fiódor Dostoyevski"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Crimen y castigo"?', '["Milan Kundera","Octavio Paz","Leo Tolstói","Fiódor Dostoyevski"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El príncipe feliz"?', '["Oscar Wilde","Agatha Christie","Gabriel García Márquez","Miguel de Unamuno"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Inés del alma mía"?', '["Pablo Neruda","Isabel Allende","Carlos Ruiz Zafón","H.P. Lovecraft"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Ternura"?', '["Albert Camus","Victor Hugo","Gabriela Mistral","Carlos Ruiz Zafón"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Asesinato en el Orient Express"?', '["Agatha Christie","Laura Esquivel","Arthur Conan Doyle","Camilo José Cela"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Agatha Christie?', '["Generación del 27","Terror cósmico","Fantasía","Novela policíaca"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "La caída de la casa Usher"?', '["Edgar Allan Poe","H.P. Lovecraft","Camilo José Cela","Antonio Machado"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Herman Melville?', '["Japonés","Italiano","Estadounidense","Británica"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El camino a Wigan Pier"?', '["George Orwell","Dan Brown","Charles Dickens","Victor Hugo"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Carlos Ruiz Zafón?', '["Británica","Español","Británico","Estadounidense"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a H.P. Lovecraft?', '["Boom latinoamericano","Terror cósmico","Vanguardismo","Fantasía"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La metamorfosis"?', '["Jane Austen","Franz Kafka","Stephen King","Laura Esquivel"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Macbeth"?', '["Haruki Murakami","Jane Austen","William Shakespeare","Suzanne Collins"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El vino del estío"?', '["Ray Bradbury","Jane Austen","Mark Twain","Umberto Eco"]'::jsonb, 0, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad chileno?', '["Pablo Neruda","Jean-Paul Sartre","Mario Vargas Llosa","Franz Kafka"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor J.R.R. Tolkien?', '["Inglés","Estadounidense","Español","Británico"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "La ley del amor"?', '["Virginia Woolf","Isaac Asimov","Charles Dickens","Laura Esquivel"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Ken Follett?', '["Fantasía épica","Novela histórica","Novela contemporánea","Novela policíaca"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La tabla de Flandes"?', '["Stephen King","Aldous Huxley","Mario Vargas Llosa","Arturo Pérez-Reverte"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El idiota"?', '["Julio Cortázar","Franz Kafka","Fiódor Dostoyevski","Herman Melville"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Los miserables"?', '["J.R.R. Tolkien","Julio Cortázar","Victor Hugo","Hermann Hesse"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Las armas secretas"?', '["Julio Cortázar","Oscar Wilde","H.P. Lovecraft","Stephen King"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Rimas y leyendas"?', '["Ray Bradbury","Isabel Allende","Albert Camus","Gustavo Adolfo Bécquer"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Otelo"?', '["Octavio Paz","Pío Baroja","Haruki Murakami","William Shakespeare"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El hacedor"?', '["Jorge Luis Borges","Pío Baroja","William Shakespeare","Juan Rulfo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Íntimas suculencias"?', '["Herman Melville","Laura Esquivel","Julio Cortázar","Isabel Allende"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El Aleph"?', '["Ray Bradbury","Haruki Murakami","Jorge Luis Borges","Mark Twain"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Octavio Paz?', '["Inglés","Ruso","Mexicano","Italiano"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La busca"?', '["Hermann Hesse","Laura Esquivel","Camilo José Cela","Pío Baroja"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El mito de Sísifo"?', '["William Shakespeare","Ray Bradbury","Fiódor Dostoyevski","Albert Camus"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Elogio de la sombra"?', '["Jorge Luis Borges","Mary Shelley","Carlos Ruiz Zafón","Bram Stoker"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Mark Twain?', '["Colombiano","Peruano","Chileno","Estadounidense"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "La dama del sudario"?', '["Bram Stoker","Miguel de Unamuno","Suzanne Collins","Arturo Pérez-Reverte"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Siddhartha"?', '["Mark Twain","Juan Rulfo","Hermann Hesse","Dan Brown"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Muerte en el Nilo"?', '["Mark Twain","Leo Tolstói","Ernest Hemingway","Agatha Christie"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor H.P. Lovecraft?', '["Checo","Británica","Alemán","Estadounidense"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Sonata a Kreutzer"?', '["Octavio Paz","Bram Stoker","Ray Bradbury","Leo Tolstói"]'::jsonb, 3, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad estadounidense?', '["Jorge Luis Borges","Dan Brown","Milan Kundera","Mary Shelley"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Ficciones"?', '["Gabriel García Márquez","Antonio Machado","Charles Dickens","Jorge Luis Borges"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Suzanne Collins?', '["Estadounidense","Ruso","Mexicana","Británico"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Poemas de las madres"?', '["Charles Dickens","Miguel de Unamuno","Ray Bradbury","Gabriela Mistral"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Veinte poemas de amor y una canción desesperada"?', '["Pablo Neruda","Suzanne Collins","Miguel de Cervantes","Octavio Paz"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La isla de las tormentas"?', '["Ken Follett","J.K. Rowling","Albert Camus","Isabel Allende"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Doña Rosita la soltera"?', '["Mary Shelley","Antonio Machado","Arthur Conan Doyle","Federico García Lorca"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "En las montañas de la locura"?', '["Jorge Luis Borges","Jane Austen","H.P. Lovecraft","Carlos Ruiz Zafón"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El cerco de Numancia"?', '["Gabriel García Márquez","Miguel de Cervantes","Suzanne Collins","Jane Austen"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Federico García Lorca?', '["Línea de fuego","Bodas de sangre","Demian","Los trabajos de Persiles y Sigismunda"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Apocalipsis"?', '["Mark Twain","Stephen King","Ray Bradbury","Gabriela Mistral"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Zalacaín el aventurero"?', '["Laura Esquivel","Antonio Machado","Pío Baroja","Mark Twain"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "David Copperfield"?', '["Gustavo Adolfo Bécquer","Antonio Machado","Charles Dickens","Miguel de Cervantes"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El príncipe de la niebla"?', '["Miguel de Cervantes","Bram Stoker","Jorge Luis Borges","Carlos Ruiz Zafón"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Mario Vargas Llosa?', '["Boom latinoamericano","Generación del 98","Ciencia ficción","Surrealismo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Al sur de la frontera, al oeste del sol"?', '["Haruki Murakami","Franz Kafka","Julio Cortázar","Mario Vargas Llosa"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Gustavo Adolfo Bécquer?', '["Terror gótico","Distopía","Vanguardismo","Romanticismo"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Omoo"?', '["J.R.R. Tolkien","Herman Melville","Carlos Ruiz Zafón","Haruki Murakami"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Federico García Lorca?', '["Generación Perdida","Romanticismo oscuro","Generación del 27","Realismo mágico"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La ignorancia"?', '["Fiódor Dostoyevski","Milan Kundera","Juan Rulfo","Agatha Christie"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Haruki Murakami?', '["Británico","Mexicano","Estadounidense","Japonés"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "La joya de las siete estrellas"?', '["Suzanne Collins","Federico García Lorca","Bram Stoker","Virginia Woolf"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El arco y la lira"?', '["Franz Kafka","Octavio Paz","Federico García Lorca","Mark Twain"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Cien años de soledad"?', '["Jorge Luis Borges","Gabriel García Márquez","Ernest Hemingway","Miguel de Unamuno"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El hombre ilustrado"?', '["Ray Bradbury","George Orwell","Stephen King","H.P. Lovecraft"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Los trabajos de Persiles y Sigismunda"?', '["Miguel de Cervantes","Jorge Luis Borges","Mario Vargas Llosa","Gabriel García Márquez"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Los juegos del hambre"?', '["Suzanne Collins","Mary Shelley","Ken Follett","Virginia Woolf"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El gallo de oro"?', '["Gustavo Adolfo Bécquer","Juan Rulfo","Herman Melville","Milan Kundera"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Soledades"?', '["Leo Tolstói","Federico García Lorca","Camilo José Cela","Antonio Machado"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El símbolo perdido"?', '["Ken Follett","Agatha Christie","Dan Brown","Gustavo Adolfo Bécquer"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad irlandés?', '["Oscar Wilde","Gabriela Mistral","Hermann Hesse","Franz Kafka"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Arthur Conan Doyle?', '["Modernismo","Novela policíaca","Distopía","Surrealismo"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El huésped de Drácula"?', '["Antonio Machado","Arthur Conan Doyle","Bram Stoker","J.K. Rowling"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Orgullo y prejuicio"?', '["Herman Melville","Milan Kundera","Jane Austen","Camilo José Cela"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Gabriela Mistral?', '["Irlandés","Chilena","Británico","Colombiano"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Antonio Machado?', '["Español","Colombiano","Británica","Mexicana"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "1Q84"?', '["Haruki Murakami","Ken Follett","Ernest Hemingway","Laura Esquivel"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El asesinato de Roger Ackroyd"?', '["Julio Cortázar","Mark Twain","Agatha Christie","Gabriela Mistral"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a George Orwell?', '["Distopía","Terror cósmico","Fantasía épica","Surrealismo"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Antonio Machado?', '["Generación del 98","Novela policíaca","Siglo de Oro","Tremendismo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Poeta en Nueva York"?', '["Stephen King","Federico García Lorca","Carlos Ruiz Zafón","J.R.R. Tolkien"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El misterio del mar"?', '["Bram Stoker","Herman Melville","Ray Bradbury","Edgar Allan Poe"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Orlando"?', '["Jean-Paul Sartre","Ernest Hemingway","Virginia Woolf","H.P. Lovecraft"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Jorge Luis Borges?', '["Mexicano","Argentino","Británico","Alemán"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Sidi"?', '["Mary Shelley","Albert Camus","Arturo Pérez-Reverte","Herman Melville"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad ruso?', '["Suzanne Collins","Leo Tolstói","George Orwell","Isabel Allende"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El gato negro"?', '["Leo Tolstói","Haruki Murakami","Miguel de Cervantes","Edgar Allan Poe"]'::jsonb, 3, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad británica?', '["Charles Dickens","William Shakespeare","J.K. Rowling","Federico García Lorca"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Lagar"?', '["Gabriela Mistral","Aldous Huxley","Ken Follett","Mary Shelley"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Isabel Allende?', '["El juego de los abalorios","Pierre o las ambigüedades","Paula","El caso de Charles Dexter Ward"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Hamlet"?', '["Mario Vargas Llosa","William Shakespeare","Umberto Eco","Oscar Wilde"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Charles Dickens?', '["Estadounidense","Español","Peruano","Británico"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Stephen King?', '["Misery","Siddhartha","La identidad","Piedra de sol"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Un cadáver en la biblioteca"?', '["Isaac Asimov","Agatha Christie","Dan Brown","Stephen King"]'::jsonb, 1, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad colombiano?', '["J.K. Rowling","George Orwell","Gabriel García Márquez","Pablo Neruda"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Carlos Ruiz Zafón?', '["Fantasía","Novela policíaca","Novela contemporánea","Ciencia ficción"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Milan Kundera?', '["Checo","Italiano","Argentino","Mexicana"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Suzanne Collins?', '["Distopía","Novela contemporánea","Ciencia ficción","Tremendismo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El signo de los cuatro"?', '["Albert Camus","Arthur Conan Doyle","Edgar Allan Poe","Charles Dickens"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Ángeles y demonios"?', '["Miguel de Unamuno","Ray Bradbury","Mary Shelley","Dan Brown"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Isabel Allende?', '["Inglés","Chilena","Francés","Irlandés"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Albert Camus?', '["Orgullo y prejuicio","Los juegos del hambre","El extranjero","El invierno del mundo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Poesías completas"?', '["Ken Follett","Antonio Machado","Stephen King","Franz Kafka"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Umberto Eco?', '["Infancia, adolescencia y juventud","Rayuela","Tiempos difíciles","Número cero"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Roverandom"?', '["Herman Melville","Ernest Hemingway","Virginia Woolf","J.R.R. Tolkien"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Milan Kundera?', '["Crónicas marcianas","El libro de la risa y el olvido","Persuasión","Historia universal de la infamia"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El proceso"?', '["Carlos Ruiz Zafón","Victor Hugo","Stephen King","Franz Kafka"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Historia de los templos de España"?', '["Gustavo Adolfo Bécquer","Fiódor Dostoyevski","Camilo José Cela","Laura Esquivel"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a William Shakespeare?', '["Generación del 98","Realismo mágico","Romanticismo","Renacimiento"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Hermann Hesse?', '["Mexicano","Francés","Japonés","Alemán"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor William Shakespeare?', '["Estadounidense","Inglés","Mexicano","Argentino"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La familia de Pascual Duarte"?', '["J.K. Rowling","Aldous Huxley","Camilo José Cela","Herman Melville"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Falkner"?', '["Victor Hugo","Pío Baroja","Mary Shelley","Jean-Paul Sartre"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Milan Kundera?', '["Terror","Distopía","Posmodernismo","Ciencia ficción"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El muro"?', '["Jean-Paul Sartre","Ray Bradbury","Virginia Woolf","Miguel de Cervantes"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Harry Potter y la piedra filosofal"?', '["J.R.R. Tolkien","Mark Twain","George Orwell","J.K. Rowling"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Relato de un náufrago"?', '["Jorge Luis Borges","Mark Twain","Leo Tolstói","Gabriel García Márquez"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Todos los fuegos el fuego"?', '["Virginia Woolf","Franz Kafka","Julio Cortázar","Suzanne Collins"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Julio Cortázar?', '["Chileno","Argentino","Mexicano","Británica"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El sabueso de los Baskerville"?', '["Arthur Conan Doyle","Oscar Wilde","J.K. Rowling","George Orwell"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Conversación en La Catedral"?', '["Gustavo Adolfo Bécquer","Mario Vargas Llosa","Octavio Paz","Pío Baroja"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Adiós a las armas"?', '["Isabel Allende","Franz Kafka","Carlos Ruiz Zafón","Ernest Hemingway"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Miguel de Cervantes?', '["Novelas ejemplares","Rebelión en la granja","Cita con la muerte","David Copperfield"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Franz Kafka?', '["Checo","Argentino","Español","Japonés"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El lobo estepario"?', '["J.R.R. Tolkien","Hermann Hesse","Herman Melville","Ernest Hemingway"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "En llamas"?', '["Umberto Eco","William Shakespeare","Bram Stoker","Suzanne Collins"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Isaac Asimov?', '["Mala hierba","Sentido y sensibilidad","Residencia en la tierra","Bóvedas de acero"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Suzanne Collins?', '["Los juegos del hambre","Historia de los templos de España","Falcó","Los cuentos de Beedle el Bardo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Pedro Páramo"?', '["Gustavo Adolfo Bécquer","William Shakespeare","Isaac Asimov","Juan Rulfo"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Ray Bradbury?', '["Muerte en el Nilo","El señor de los anillos","Las doradas manzanas del sol","Final del juego"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Travesuras de la niña mala"?', '["Ray Bradbury","Franz Kafka","Mark Twain","Mario Vargas Llosa"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Estrellita marinera"?', '["Gustavo Adolfo Bécquer","Laura Esquivel","Mario Vargas Llosa","Antonio Machado"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Los años"?', '["Dan Brown","Ernest Hemingway","Virginia Woolf","Julio Cortázar"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Origen"?', '["Julio Cortázar","Victor Hugo","Antonio Machado","Dan Brown"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El noventa y tres"?', '["Victor Hugo","Albert Camus","Hermann Hesse","Oscar Wilde"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor J.K. Rowling?', '["Chileno","Británica","Checo","Japonés"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Isabel Allende?', '["Thriller","Terror","Vanguardismo","Realismo mágico"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Albert Camus?', '["Irlandés","Francés","Italiano","Argentino"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El nombre de la rosa"?', '["Agatha Christie","Ken Follett","Mark Twain","Umberto Eco"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Pantaleón y las visitadoras"?', '["Ray Bradbury","Milan Kundera","Mario Vargas Llosa","Aldous Huxley"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Victor Hugo?', '["Estadounidense","Francés","Checo","Japonés"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Aldous Huxley?', '["Existencialismo","Distopía","Esteticismo","Boom latinoamericano"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Oscar Wilde?', '["Japonés","Irlandés","Alemán","Español"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El juego del ángel"?', '["Franz Kafka","Dan Brown","Carlos Ruiz Zafón","Ken Follett"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Harry Potter y el prisionero de Azkaban"?', '["Gabriela Mistral","Milan Kundera","Stephen King","J.K. Rowling"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Oscar Wilde?', '["Esteticismo","Tremendismo","Generación del 98","Fantasía"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Virginia Woolf?', '["Árbol adentro","Final del juego","Una habitación propia","El hombre ilustrado"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "A puerta cerrada"?', '["Julio Cortázar","Umberto Eco","Jean-Paul Sartre","Ken Follett"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Gabriela Mistral?', '["El nombre de la rosa","Ternura","La abadía de Northanger","Anna Karénina"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Aurora roja"?', '["Camilo José Cela","Pío Baroja","Herman Melville","Arthur Conan Doyle"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Pablo Neruda?', '["Boom latinoamericano","Generación Perdida","Vanguardismo","Esteticismo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "San Camilo, 1936"?', '["Mario Vargas Llosa","Virginia Woolf","Camilo José Cela","Stephen King"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Falcó"?', '["Leo Tolstói","Mark Twain","Isaac Asimov","Arturo Pérez-Reverte"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Los pilares de la Tierra"?', '["Gabriela Mistral","Ken Follett","Miguel de Cervantes","Bram Stoker"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El libro de arena"?', '["Miguel de Cervantes","Jorge Luis Borges","Gabriela Mistral","Jean-Paul Sartre"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La caída de los gigantes"?', '["Ken Follett","Miguel de Unamuno","Arthur Conan Doyle","Oscar Wilde"]'::jsonb, 0, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad peruano?', '["Jean-Paul Sartre","Miguel de Unamuno","Dan Brown","Mario Vargas Llosa"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Persuasión"?', '["Octavio Paz","Suzanne Collins","Julio Cortázar","Jane Austen"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El hobbit"?', '["J.R.R. Tolkien","Pío Baroja","Agatha Christie","George Orwell"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Niebla"?', '["Carlos Ruiz Zafón","Miguel de Unamuno","J.K. Rowling","Julio Cortázar"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Juan Rulfo?', '["Alemán","Estadounidense","Mexicano","Colombiano"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Ernest Hemingway?', '["Mexicano","Chileno","Estadounidense","Español"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La inmortalidad"?', '["Ken Follett","Milan Kundera","Herman Melville","Ray Bradbury"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Demian"?', '["Hermann Hesse","Aldous Huxley","Julio Cortázar","Edgar Allan Poe"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Residencia en la tierra"?', '["Pablo Neruda","Federico García Lorca","Pío Baroja","Bram Stoker"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Mansfield Park"?', '["Mario Vargas Llosa","Fiódor Dostoyevski","Jane Austen","William Shakespeare"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El invierno del mundo"?', '["Ernest Hemingway","H.P. Lovecraft","Ken Follett","Pío Baroja"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Charles Dickens?', '["El primer hombre","Persuasión","Cuento de Navidad","Los crímenes de la calle Morgue"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Un yanqui en la corte del rey Arturo"?', '["Ken Follett","Mark Twain","Agatha Christie","Pío Baroja"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Edgar Allan Poe?', '["Los crímenes de la calle Morgue","Sputnik, mi amor","Muerte en el Nilo","El umbral de la eternidad"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Laura Esquivel?', '["Romanticismo","Realismo mágico","Generación del 27","Vanguardismo"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Octavio Paz?', '["Sentido y sensibilidad","Sor Juana Inés de la Cruz o las trampas de la fe","Poeta en Nueva York","La fiesta del chivo"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Dan Brown?', '["Estadounidense","Checo","Británica","Irlandés"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Tala"?', '["H.P. Lovecraft","Gabriela Mistral","Gabriel García Márquez","Arturo Pérez-Reverte"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Camilo José Cela?', '["Japonés","Irlandés","Checo","Español"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Número cero"?', '["Haruki Murakami","Gabriela Mistral","Octavio Paz","Umberto Eco"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Jean-Paul Sartre?', '["Esteticismo","Terror cósmico","Existencialismo","Fantasía épica"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Jorge Luis Borges?', '["Posmodernismo","Novela policíaca","Thriller","Vanguardismo"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Antonio Machado?', '["Gregor la profecía del gris","El retrato de Dorian Gray","Nuevas canciones","David Copperfield"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El prisionero del cielo"?', '["Carlos Ruiz Zafón","Miguel de Unamuno","Charles Dickens","William Shakespeare"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Jean-Paul Sartre?', '["Peruano","Francés","Japonés","Mexicano"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Los caminos de la libertad"?', '["Bram Stoker","Charles Dickens","Jean-Paul Sartre","Dan Brown"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Calígula"?', '["Aldous Huxley","Ken Follett","Albert Camus","J.R.R. Tolkien"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Isaac Asimov?', '["Siglo de Oro","Ciencia ficción","Realismo","Terror gótico"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Una habitación propia"?', '["Isaac Asimov","Virginia Woolf","Mary Shelley","Antonio Machado"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Sinsajo"?', '["Hermann Hesse","Virginia Woolf","Gabriel García Márquez","Suzanne Collins"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Mathilda"?', '["Camilo José Cela","Laura Esquivel","Mary Shelley","Bram Stoker"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Mark Twain?', '["Generación Perdida","Realismo","Fantasía","Realismo mágico"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Mary Shelley?', '["Mathilda","La sombra sobre Innsmouth","Inés del alma mía","El Llano en llamas"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Juan Rulfo?', '["La dama del sudario","El gallo de oro","El fin de la eternidad","Las doradas manzanas del sol"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por J.K. Rowling?', '["Narciso y Goldmundo","La familia de Pascual Duarte","Demian","Animales fantásticos y dónde encontrarlos"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "De profundis"?', '["Oscar Wilde","Arthur Conan Doyle","Mary Shelley","Jane Austen"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "De amor y de sombra"?', '["Octavio Paz","Juan Rulfo","Miguel de Unamuno","Isabel Allende"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Isaac Asimov?', '["Ruso","Argentino","Mexicano","Estadounidense"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El último hombre"?', '["Herman Melville","William Shakespeare","Mary Shelley","Juan Rulfo"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad italiano?', '["Jane Austen","Umberto Eco","Juan Rulfo","Mary Shelley"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Agatha Christie?', '["Un cadáver en la biblioteca","Mono y esencia","Noticia de un secuestro","El símbolo perdido"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La broma"?', '["Fiódor Dostoyevski","Milan Kundera","Miguel de Unamuno","Laura Esquivel"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Mala hierba"?', '["Ray Bradbury","Oscar Wilde","Gabriela Mistral","Pío Baroja"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Las aventuras de Huckleberry Finn"?', '["Mark Twain","George Orwell","Mario Vargas Llosa","Umberto Eco"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Mary Shelley?', '["Novela policíaca","Ciencia ficción","Renacimiento","Romanticismo"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Árbol adentro"?', '["Octavio Paz","Stephen King","Agatha Christie","William Shakespeare"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Noticia de un secuestro"?', '["Gabriel García Márquez","Mark Twain","Antonio Machado","Umberto Eco"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Las puertas de la percepción"?', '["Aldous Huxley","Bram Stoker","Jane Austen","Herman Melville"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Camilo José Cela?', '["Las nieves del Kilimanjaro","La colmena","Asesinato en el Orient Express","El fin de la eternidad"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Laura Esquivel?', '["La abadía de Northanger","Íntimas suculencias","El prisionero del cielo","El fin de la eternidad"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Pierre o las ambigüedades"?', '["Herman Melville","Jean-Paul Sartre","Mario Vargas Llosa","Milan Kundera"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Bajo las ruedas"?', '["H.P. Lovecraft","Arthur Conan Doyle","Virginia Woolf","Hermann Hesse"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Ray Bradbury?', '["Novela policíaca","Terror","Ciencia ficción","Fantasía"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Nuestra Señora de París"?', '["Mario Vargas Llosa","Victor Hugo","Federico García Lorca","Ken Follett"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El valle del terror"?', '["Miguel de Unamuno","William Shakespeare","Arthur Conan Doyle","Ernest Hemingway"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Viaje a la Alcarria"?', '["Antonio Machado","Camilo José Cela","Federico García Lorca","Pablo Neruda"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Victor Hugo?', '["El nombre de la rosa","Roverandom","El castillo","Los trabajadores del mar"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Línea de fuego"?', '["Stephen King","Haruki Murakami","Arturo Pérez-Reverte","Gabriel García Márquez"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Gustavo Adolfo Bécquer?', '["Italiano","Checo","Británica","Español"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Arthur Conan Doyle?', '["El mundo perdido","El cuervo","El rey Lear","Paula"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Octavio Paz?', '["Novela policíaca","Modernismo","Ciencia ficción","Surrealismo"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El mundo perdido"?', '["Dan Brown","Bram Stoker","Jane Austen","Arthur Conan Doyle"]'::jsonb, 3, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad británico?', '["Gustavo Adolfo Bécquer","William Shakespeare","Aldous Huxley","Herman Melville"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Arturo Pérez-Reverte?', '["Estudio en escarlata","Falcó","Viaje a la Alcarria","Historia de dos ciudades"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La casa de Bernarda Alba"?', '["Julio Cortázar","Gabriel García Márquez","Federico García Lorca","Franz Kafka"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Crónica del pájaro que da cuerda al mundo"?', '["William Shakespeare","George Orwell","Haruki Murakami","Isabel Allende"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Paula"?', '["Antonio Machado","Isabel Allende","Gabriel García Márquez","Bram Stoker"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Ernest Hemingway?', '["Existencialismo","Esteticismo","Fantasía","Generación Perdida"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Gabriela Mistral?', '["Romanticismo","Realismo mágico","Posmodernismo","Existencialismo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Frankenstein"?', '["Federico García Lorca","Herman Melville","Bram Stoker","Mary Shelley"]'::jsonb, 3, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad japonés?', '["Ken Follett","Agatha Christie","Haruki Murakami","Hermann Hesse"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Piedra de sol"?', '["Gustavo Adolfo Bécquer","Umberto Eco","Octavio Paz","Mark Twain"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El castillo"?', '["Franz Kafka","Agatha Christie","Arthur Conan Doyle","J.K. Rowling"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La sombra del viento"?', '["Carlos Ruiz Zafón","William Shakespeare","Hermann Hesse","Bram Stoker"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Jorge Luis Borges?', '["Elogio de la sombra","Narciso y Goldmundo","Orlando","Abel Sánchez"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Novelas ejemplares"?', '["Agatha Christie","Miguel de Cervantes","Laura Esquivel","Julio Cortázar"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Cita con la muerte"?', '["Edgar Allan Poe","Isaac Asimov","Leo Tolstói","Agatha Christie"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Lodore"?', '["Ernest Hemingway","Mark Twain","Mary Shelley","Camilo José Cela"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La colmena"?', '["Albert Camus","J.R.R. Tolkien","Jean-Paul Sartre","Camilo José Cela"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Fundación e Imperio"?', '["Jane Austen","Isaac Asimov","H.P. Lovecraft","Stephen King"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El árbol de la ciencia"?', '["Mark Twain","Arturo Pérez-Reverte","Isaac Asimov","Pío Baroja"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Las nieves del Kilimanjaro"?', '["Antonio Machado","Federico García Lorca","Ernest Hemingway","Carlos Ruiz Zafón"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Crónica de una muerte anunciada"?', '["Pablo Neruda","H.P. Lovecraft","Agatha Christie","Gabriel García Márquez"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Sentido y sensibilidad"?', '["Jane Austen","Isaac Asimov","Virginia Woolf","Octavio Paz"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Franz Kafka?', '["Omoo","La isla del día de antes","Carta al padre","Otelo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Campos de Castilla"?', '["Bram Stoker","Isaac Asimov","Antonio Machado","Carlos Ruiz Zafón"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Tiempos difíciles"?', '["Octavio Paz","Dan Brown","Hermann Hesse","Charles Dickens"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El cuervo"?', '["Edgar Allan Poe","Hermann Hesse","Victor Hugo","Suzanne Collins"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Sor Juana Inés de la Cruz o las trampas de la fe"?', '["Octavio Paz","Fiódor Dostoyevski","J.K. Rowling","Mary Shelley"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Herman Melville?', '["Bestiario","Lagar","El jugador","Pierre o las ambigüedades"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Yerma"?', '["Mark Twain","Arturo Pérez-Reverte","Julio Cortázar","Federico García Lorca"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Juan Rulfo?', '["Romanticismo","Ciencia ficción","Fantasía épica","Realismo mágico"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "La sombra sobre Innsmouth"?', '["Laura Esquivel","J.K. Rowling","H.P. Lovecraft","Dan Brown"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Romeo y Julieta"?', '["Isaac Asimov","Mark Twain","William Shakespeare","Julio Cortázar"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Ken Follett?', '["Chileno","Japonés","Británico","Inglés"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Jane Austen?', '["Nuestra Señora de París","Emma","Sueño de una noche de verano","El príncipe de la niebla"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "1984"?', '["George Orwell","Mary Shelley","J.R.R. Tolkien","Juan Rulfo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La vida en el Misisipi"?', '["Miguel de Unamuno","Herman Melville","Mark Twain","Carlos Ruiz Zafón"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El horror de Dunwich"?', '["Laura Esquivel","Edgar Allan Poe","Antonio Machado","H.P. Lovecraft"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Amor y pedagogía"?', '["Gustavo Adolfo Bécquer","Fiódor Dostoyevski","H.P. Lovecraft","Miguel de Unamuno"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Mario Vargas Llosa?', '["Peruano","Japonés","Británico","Español"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Los propios dioses"?', '["Octavio Paz","Isaac Asimov","Jorge Luis Borges","Suzanne Collins"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Cartas desde mi celda"?', '["Isaac Asimov","Octavio Paz","Mark Twain","Gustavo Adolfo Bécquer"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Bartleby, el escribiente"?', '["Juan Rulfo","Gustavo Adolfo Bécquer","Herman Melville","H.P. Lovecraft"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El fin de la eternidad"?', '["J.K. Rowling","Isaac Asimov","Franz Kafka","Miguel de Unamuno"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Los crímenes de la calle Morgue"?', '["Edgar Allan Poe","Dan Brown","Ken Follett","Jorge Luis Borges"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Aldous Huxley?', '["Ruso","Mexicana","Británico","Checo"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Arturo Pérez-Reverte?', '["Chilena","Colombiano","Español","Chileno"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La caída"?', '["Antonio Machado","William Shakespeare","Virginia Woolf","Albert Camus"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Tokio blues"?', '["Laura Esquivel","Federico García Lorca","Haruki Murakami","Octavio Paz"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La guarida del gusano blanco"?', '["Ernest Hemingway","Arthur Conan Doyle","Bram Stoker","Ken Follett"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad mexicano?', '["Juan Rulfo","Milan Kundera","Camilo José Cela","Herman Melville"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Julio Cortázar?', '["Boom latinoamericano","Renacimiento","Tremendismo","Terror"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Bram Stoker?', '["Por quién doblan las campanas","El fin de la eternidad","Falcó","La joya de las siete estrellas"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Ken Follett?', '["El sabueso de los Baskerville","En llamas","Infancia, adolescencia y juventud","La caída de los gigantes"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Typee"?', '["Herman Melville","Arthur Conan Doyle","Umberto Eco","Arturo Pérez-Reverte"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El príncipe y el mendigo"?', '["Edgar Allan Poe","Gabriel García Márquez","Julio Cortázar","Mark Twain"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El hombre que ríe"?', '["Jane Austen","H.P. Lovecraft","Victor Hugo","Camilo José Cela"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Mark Twain?', '["Las aventuras de Sherlock Holmes","Las aventuras de Huckleberry Finn","Las moscas","Memorias del subsuelo"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Bodas de sangre"?', '["Federico García Lorca","Isabel Allende","Edgar Allan Poe","Julio Cortázar"]'::jsonb, 0, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Dan Brown?', '["Thriller","Boom latinoamericano","Romanticismo oscuro","Realismo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Inferno"?', '["Carlos Ruiz Zafón","Dan Brown","Stephen King","William Shakespeare"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Agatha Christie?', '["Inglés","Británica","Peruano","Chilena"]'::jsonb, 1, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad francés?', '["Juan Rulfo","Carlos Ruiz Zafón","George Orwell","Albert Camus"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Umberto Eco?', '["Británica","Francés","Italiano","Español"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Virginia Woolf?', '["Ruso","Británica","Chileno","Estadounidense"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Balada de pájaros cantores y serpientes"?', '["Umberto Eco","Oscar Wilde","Suzanne Collins","Federico García Lorca"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La isla"?', '["Fiódor Dostoyevski","Umberto Eco","Agatha Christie","Aldous Huxley"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Rebelión en la granja"?', '["Antonio Machado","Jean-Paul Sartre","George Orwell","Herman Melville"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Misery"?', '["Albert Camus","Carlos Ruiz Zafón","Stephen King","Ken Follett"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Bóvedas de acero"?', '["Jane Austen","Isaac Asimov","Arthur Conan Doyle","Antonio Machado"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Cien sonetos de amor"?', '["Pablo Neruda","Octavio Paz","Pío Baroja","Mario Vargas Llosa"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Gustavo Adolfo Bécquer?', '["Nuevas canciones","Carrie","Pedro Páramo","Cartas desde mi celda"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Sueño de una noche de verano"?', '["Isabel Allende","Edgar Allan Poe","Federico García Lorca","William Shakespeare"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Historia de dos ciudades"?', '["Isabel Allende","Laura Esquivel","Jorge Luis Borges","Charles Dickens"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por George Orwell?', '["Homenaje a Cataluña","Confieso que he vivido","Cartas desde mi celda","El príncipe de la niebla"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Fiódor Dostoyevski?', '["Alemán","Francés","Ruso","Japonés"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Jane Austen?', '["Surrealismo","Romanticismo","Renacimiento","Boom latinoamericano"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "La casa de los espíritus"?', '["Gabriela Mistral","Mark Twain","Victor Hugo","Isabel Allende"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Miguel de Unamuno?', '["Del sentimiento trágico de la vida","La isla","El club Dumas","Pantaleón y las visitadoras"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El coronel no tiene quien le escriba"?', '["Gabriel García Márquez","William Shakespeare","Bram Stoker","Laura Esquivel"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La ciudad y los perros"?', '["Gabriel García Márquez","Mario Vargas Llosa","Suzanne Collins","H.P. Lovecraft"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Crónicas marcianas"?', '["Virginia Woolf","Agatha Christie","Ray Bradbury","Gustavo Adolfo Bécquer"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Edgar Allan Poe?', '["Romanticismo oscuro","Romanticismo","Distopía","Terror cósmico"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La muerte de Iván Ilich"?', '["Umberto Eco","Fiódor Dostoyevski","Leo Tolstói","Herman Melville"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Virginia Woolf?', '["Modernismo","Generación del 98","Esteticismo","Vanguardismo"]'::jsonb, 0, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Mario Vargas Llosa?', '["1Q84","Infancia, adolescencia y juventud","La isla","Pantaleón y las visitadoras"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Baudolino"?', '["Albert Camus","Ken Follett","Hermann Hesse","Umberto Eco"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El rey Lear"?', '["Miguel de Unamuno","William Shakespeare","H.P. Lovecraft","Carlos Ruiz Zafón"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Pobres gentes"?', '["Franz Kafka","Miguel de Cervantes","Herman Melville","Fiódor Dostoyevski"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El color que cayó del cielo"?', '["Mary Shelley","Milan Kundera","Albert Camus","H.P. Lovecraft"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Los trabajadores del mar"?', '["Arthur Conan Doyle","Victor Hugo","Hermann Hesse","Stephen King"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Canto General"?', '["Bram Stoker","Fiódor Dostoyevski","Pablo Neruda","Virginia Woolf"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Los días de Birmania"?', '["George Orwell","Isabel Allende","Jean-Paul Sartre","Arturo Pérez-Reverte"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Los hijos de Húrin"?', '["Leo Tolstói","Ray Bradbury","J.R.R. Tolkien","Virginia Woolf"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad checo?', '["Jane Austen","Suzanne Collins","George Orwell","Franz Kafka"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Cementerio de animales"?', '["Stephen King","Arturo Pérez-Reverte","Haruki Murakami","Hermann Hesse"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Las doradas manzanas del sol"?', '["Jean-Paul Sartre","Ray Bradbury","Laura Esquivel","Fiódor Dostoyevski"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Pablo Neruda?', '["Italiano","Japonés","Chileno","Francés"]'::jsonb, 2, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Pablo Neruda?', '["Mala hierba","Orlando","Al faro","Cien sonetos de amor"]'::jsonb, 3, 'Literatura'),
('¿De qué nacionalidad es el autor Mary Shelley?', '["Mexicana","Británico","Irlandés","Británica"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El extranjero"?', '["Arthur Conan Doyle","Albert Camus","Aldous Huxley","Isabel Allende"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a J.K. Rowling?', '["Generación del 27","Terror","Fantasía","Generación Perdida"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "La importancia de llamarse Ernesto"?', '["Dan Brown","Arthur Conan Doyle","Oscar Wilde","Miguel de Cervantes"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El árbol de las brujas"?', '["Ken Follett","J.K. Rowling","Ray Bradbury","H.P. Lovecraft"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Bram Stoker?', '["Mexicano","Chilena","Irlandés","Inglés"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Don Quijote de la Mancha"?', '["Agatha Christie","Miguel de Cervantes","Ken Follett","Aldous Huxley"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Como agua para chocolate"?', '["Laura Esquivel","Jane Austen","Juan Rulfo","William Shakespeare"]'::jsonb, 0, 'Literatura'),
('¿De qué nacionalidad es el autor Ray Bradbury?', '["Japonés","Argentino","Estadounidense","Ruso"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El jugador"?', '["Oscar Wilde","Arturo Pérez-Reverte","Fiódor Dostoyevski","Albert Camus"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad inglés?', '["William Shakespeare","Federico García Lorca","Camilo José Cela","Pablo Neruda"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "El club Dumas"?', '["Suzanne Collins","Juan Rulfo","Arturo Pérez-Reverte","Arthur Conan Doyle"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Carrie"?', '["Agatha Christie","H.P. Lovecraft","Stephen King","Fiódor Dostoyevski"]'::jsonb, 2, 'Literatura'),
('¿Cuál de estos autores es de nacionalidad español?', '["Federico García Lorca","Oscar Wilde","Pablo Neruda","William Shakespeare"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "La fiesta del chivo"?', '["Fiódor Dostoyevski","Mario Vargas Llosa","Pío Baroja","Mary Shelley"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "El cementerio de Praga"?', '["Gabriela Mistral","Umberto Eco","Agatha Christie","Oscar Wilde"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Del sentimiento trágico de la vida"?', '["Mary Shelley","Carlos Ruiz Zafón","Bram Stoker","Miguel de Unamuno"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Haruki Murakami?', '["Generación Perdida","Novela contemporánea","Realismo mágico","Romanticismo"]'::jsonb, 2, 'Literatura'),
('¿De qué nacionalidad es el autor Jane Austen?', '["Alemán","Irlandés","Británica","Mexicana"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Pabellón de reposo"?', '["Camilo José Cela","Oscar Wilde","Pablo Neruda","Jean-Paul Sartre"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Mazurca para dos muertos"?', '["Federico García Lorca","Mary Shelley","Julio Cortázar","Camilo José Cela"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "La Galatea"?', '["Miguel de Cervantes","Hermann Hesse","Mary Shelley","Juan Rulfo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Nuevas canciones"?', '["Federico García Lorca","Mark Twain","Leo Tolstói","Antonio Machado"]'::jsonb, 3, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Carlos Ruiz Zafón?', '["La sombra del viento","Zalacaín el aventurero","Animales fantásticos y dónde encontrarlos","El castillo"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Juan de Mairena"?', '["Suzanne Collins","Antonio Machado","Hermann Hesse","Ernest Hemingway"]'::jsonb, 1, 'Literatura'),
('¿Cuál de las siguientes obras fue escrita por Leo Tolstói?', '["Un cadáver en la biblioteca","Infancia, adolescencia y juventud","El forastero misterioso","La metamorfosis"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Herman Melville?', '["Realismo mágico","Romanticismo","Modernismo","Fantasía épica"]'::jsonb, 1, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Stephen King?', '["Esteticismo","Generación del 98","Terror","Tremendismo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Un mundo sin fin"?', '["Ken Follett","Suzanne Collins","Leo Tolstói","Ray Bradbury"]'::jsonb, 0, 'Literatura'),
('¿Quién es el autor de "Cuentos de Eva Luna"?', '["Ray Bradbury","Gabriel García Márquez","Ken Follett","Isabel Allende"]'::jsonb, 3, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Arturo Pérez-Reverte?', '["Generación del 27","Posmodernismo","Novela histórica","Fantasía épica"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Albert Camus?', '["Generación del 27","Existencialismo","Terror cósmico","Generación del 98"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Un mundo feliz"?', '["Ernest Hemingway","Aldous Huxley","Agatha Christie","Mary Shelley"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor Arthur Conan Doyle?', '["Mexicana","Británico","Inglés","Chileno"]'::jsonb, 1, 'Literatura'),
('¿Quién es el autor de "Cuentos inconclusos de Númenor y la Tierra Media"?', '["Victor Hugo","J.K. Rowling","Haruki Murakami","J.R.R. Tolkien"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El primer hombre"?', '["Edgar Allan Poe","Carlos Ruiz Zafón","Albert Camus","Victor Hugo"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Marina"?', '["J.R.R. Tolkien","Juan Rulfo","Carlos Ruiz Zafón","Arturo Pérez-Reverte"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "Los cuentos de Beedle el Bardo"?', '["Jean-Paul Sartre","J.K. Rowling","Oscar Wilde","Suzanne Collins"]'::jsonb, 1, 'Literatura'),
('¿De qué nacionalidad es el autor George Orwell?', '["Peruano","Chileno","Británica","Británico"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Valperga"?', '["Hermann Hesse","Franz Kafka","Aldous Huxley","Mary Shelley"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "La náusea"?', '["Fiódor Dostoyevski","J.K. Rowling","Federico García Lorca","Jean-Paul Sartre"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "El amor en los tiempos del cólera"?', '["Antonio Machado","Pío Baroja","Charles Dickens","Gabriel García Márquez"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Abel Sánchez"?', '["Isaac Asimov","William Shakespeare","Miguel de Unamuno","Isabel Allende"]'::jsonb, 2, 'Literatura'),
('¿Quién es el autor de "El laberinto de los espíritus"?', '["Franz Kafka","Suzanne Collins","H.P. Lovecraft","Carlos Ruiz Zafón"]'::jsonb, 3, 'Literatura'),
('¿Quién es el autor de "Yo, robot"?', '["Agatha Christie","Leo Tolstói","Isaac Asimov","Miguel de Cervantes"]'::jsonb, 2, 'Literatura'),
('¿A qué movimiento o época literaria se asocia principalmente a Victor Hugo?', '["Modernismo","Realismo mágico","Romanticismo","Fantasía épica"]'::jsonb, 2, 'Literatura');